const Polo = [
  {
    img: "https://m.media-amazon.com/images/I/51xOEh5DKYL._SY879_.jpg",
    img2: "https://m.media-amazon.com/images/I/91DGqjA4qEL._SX569_.jpg",
    title: "Van Heusen Men's Solid Polo T Shirt",
    price: "₹599",
    rating: "4",
    dimensions: " 27 x 22 x 0.5 cm; 250 g",
  },
  {
    img: "https://m.media-amazon.com/images/I/71eUwDk8z+L._SY879_.jpg",
    img2: "https://m.media-amazon.com/images/I/71vSLpVgZpL._SX569_.jpg",
    title: "Allen Solly Men's Solid Regular Fit Polo",
    price: "₹629",
    rating: "4.1",
    dimensions: "28 x 27 x 2 cm; 350 g",
  },
  {
    img: "https://m.media-amazon.com/images/I/91xBAXPM+JL._SY879_.jpg",
    img2: "https://m.media-amazon.com/images/I/91gz4Tc13kL._SX569_.jpg",
    title: "Allen Solly Men's Regular Fit Polo",
    price: "₹599",
    rating: "4.1",
    dimensions: "25 x 20 x 2 cm; 200 g",
  },
  {
    img: "https://m.media-amazon.com/images/I/61tH-hpDSJL._SY879_.jpg",
    img2: "https://m.media-amazon.com/images/I/810vW4bwkRL._SY741_.jpg",
    title: "Max Men's Half Sleeves Regular Fit Polo",
    price: "₹399",
    rating: "4.7",
    dimensions: "16 x 12 x 5 cm; 250 g",
  },
  {
    img: "https://m.media-amazon.com/images/I/61rLmeQiP9L._SY879_.jpg",
    img2: "https://m.media-amazon.com/images/I/61UmgNKX71L._SY741_.jpg",
    title: "Max Men's Half Sleeves Regular Fit",
    price: " ₹549",
    rating: "5.0",
    dimensions: "16 x 12 x 5 cm; 250 g",
  },
  {
    img: "https://m.media-amazon.com/images/I/61hZ4Lw4LAL._SY879_.jpg",
    img2: "https://m.media-amazon.com/images/I/6176toPUxOL._SY741_.jpg",
    title: "Max Men's Half Sleeves Regular Fit Collared Neck Polo",
    price: "₹359",
    rating: "4.0",
    dimensions: "16 x 12 x 5 cm; 250 g",
  },
];
export default Polo;
